### ISSUE TITLE
Will this even run?

### ISSUE THREAD

**Issue by JustAShoeMaker** [SumoLogic/collector-management-client#14]
OK. I was thinking about using this at work, and read through it. But will it work? Or I caught it at a weird in-between Py2 and Py3 and master is most up to date ?

Just a read through has me confused, and it might be my skill level.  But.

1) `izip_longest` disappears in Python 3
2) `raw_input` also
3) but then it uses `print()` and not `print` but no `from __future__ import print_function` import.

**Comment by rvmiller89** [comment]
Hi @JustAShoeMaker  we worked on improving the Python2/3 support in https://github.com/SumoLogic/collector-management-client/pull/16.

Please re-open if you have any issue.
