### ISSUE TITLE
the category filter seems broken

### ISSUE THREAD

**Issue by cory-sumo** [SumoLogic/collector-management-client#6]
Traceback (most recent call last):
  File "sumo_mgmt.py", line 527, in <module>
    collectors = filter_collectors(collectors)
  File "sumo_mgmt.py", line 464, in filter_collectors
    return list(filter_by(collector_list, {filter_type: condition}))
  File "sumo_mgmt.py", line 420, in filter_by
    if not re.match('^' + str(pairs[key]) + '$', str(elem[key]), flags=0): 
KeyError: 'category'

Command I ran: 
python sumo_mgmt.py -url https://api.sumologic.com/api/v1/ -accessid <id> -accesskey <key> -filter category=dev -listVersions

**Comment by rvmiller89** [comment]
fixed in https://github.com/SumoLogic/collector-management-client/pull/7
